### ISSUE TITLE
Improper user input validation 

### ISSUE THREAD

**Issue by Tibinsunny** [AnkushSinghGandhi/profile-chrome-extension#4]
### Description

Hey,
I just found that the extension is not properly handling user inputs which leads to html injection . 

Steps to reproduce:
Just add `"><font color="red">HTML</font>  ` as user name 

### Screenshots

![HTML-Inject-Hacktober](https://user-images.githubusercontent.com/33937416/137635255-d1b87203-8f85-4731-9ab0-678b02fdf3c7.PNG)

### Additional information

I am currently working on the fix. I'll soon make a Pull Request for this

**Comment by AnkushSinghGandhi** [comment]
Now closing this issue.
